version: '3'
services:

  minio:
    image: bitnami/minio:latest
    hostname: minio
    restart: always
#    healthcheck:
#      test: curl -f http://localhost:9000/ || exit 1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./minio:/minio
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - bridge

#  minio-create-bucket:
#    image: minio/mc
#    depends_on:
#      - minio
#    entrypoint: >
#      /bin/sh -c "
#      until (/usr/bin/mc config host add myminio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
#      /usr/bin/mc mb myminio/processed-data;
#      /usr/bin/mc policy download myminio/processed-data;
#      exit 0;
#      "

  api:
    image: ${image_name}
    #    environment:
    #      - ENV=develop
    depends_on:
      minio:
        condition: service_healthy
    ports:
      - 8080:8080
#    command: run
    volumes:
      - ..:/app
    networks:
      - bridge

#networks:
#  default:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 127.0.0.1/24
networks:
  bridge:
   driver: bridge
#networks:
#  resolute:
#    external:
#      name: resolute