version: '3'
services:

  minio:
    image: bitnami/minio:latest
    hostname: minio
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./minio:/minio
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - bridge


  api:
    image: ${image_name}
    #    environment:
    #      - ENV=develop
    depends_on:
      minio:
        condition: service_healthy
    ports:
      - 8080:8080
#    command: run
    volumes:
      - ..:/app
    networks:
      - bridge

networks:
  bridge:
   driver: bridge