version: '3'
services:
  minio:
    image: bitnami/minio:latest
    hostname: minio
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./minio:/minio
    ports:
      - 9000:9000
      - 9001:9001

  minio-create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/datalake;
      /usr/bin/mc policy download myminio/datalake;
      exit 0;
      "
